{{--
    Konfigurasi Tailwind CSS bersama.
    Di-include dari semua layout agar token warna & tipografi konsisten.
--}}
<script>
    tailwind.config = {
        darkMode: "class",
        theme: {
            extend: {
                spacing: {
                    'space-2xs': '0.25rem',
                    'space-xs':  '0.5rem',
                    'space-sm':  '0.75rem',
                    'space-md':  '1rem',
                    'space-lg':  '1.5rem',
                    'space-xl':  '2rem',
                    'space-2xl': '3rem',
                },
                colors: {
                    "on-primary-container":       "#fdfcff",
                    "on-tertiary":                "#ffffff",
                    "surface-container-highest":  "#d3e4fe",
                    "on-primary":                 "#ffffff",
                    "inverse-surface":            "#213145",
                    "inverse-primary":            "#93ccff",
                    "surface-container":          "#e5eeff",
                    "tertiary":                   "#006947",
                    "tertiary-container":         "#00855b",
                    "primary":                    "#006194",
                    "inverse-on-surface":         "#eaf1ff",
                    "on-surface-variant":         "#3f4850",
                    "on-secondary-container":     "#004666",
                    "outline":                    "#707881",
                    "primary-fixed-dim":          "#93ccff",
                    "on-primary-fixed-variant":   "#004b73",
                    "on-background":              "#0b1c30",
                    "on-surface":                 "#0b1c30",
                    "surface-dim":                "#cbdbf5",
                    "surface-tint":               "#006398",
                    "surface-bright":             "#f8f9ff",
                    "surface-variant":            "#d3e4fe",
                    "error-container":            "#ffdad6",
                    "outline-variant":            "#bfc7d2",
                    "error":                      "#ba1a1a",
                    "on-primary-fixed":           "#001d31",
                    "secondary":                  "#006591",
                    "on-secondary":               "#ffffff",
                    "on-tertiary-fixed":          "#002113",
                    "secondary-fixed-dim":        "#89ceff",
                    "primary-fixed":              "#cce5ff",
                    "background":                 "#f8f9ff",
                    "on-tertiary-fixed-variant":  "#005236",
                    "primary-container":          "#007bb9",
                    "tertiary-fixed":             "#6ffbbe",
                    "surface-container-high":     "#dce9ff",
                    "secondary-container":        "#39b8fd",
                    "surface":                    "#f8f9ff",
                    "surface-container-low":      "#eff4ff",
                    "secondary-fixed":            "#c9e6ff",
                    "tertiary-fixed-dim":         "#4edea3",
                    "on-error-container":         "#93000a",
                    "on-error":                   "#ffffff",
                    "surface-container-lowest":   "#ffffff",
                    "on-secondary-fixed":         "#001e2f",
                    "on-secondary-fixed-variant": "#004c6e",
                    "on-tertiary-container":      "#f5fff6",
                },
                fontFamily: {
                    "headline-md":  ["Space Grotesk"],
                    "display-hero": ["Space Grotesk"],
                    "headline-xl":  ["Space Grotesk"],
                    "headline-lg":  ["Space Grotesk"],
                    "body-md":      ["Geist"],
                    "body-sm":      ["Geist"],
                    "body-lg":      ["Geist"],
                    "code-editor":  ["JetBrains Mono"],
                    "label-badge":  ["JetBrains Mono"],
                    "code-inline":  ["JetBrains Mono"],
                    "title-sm":     ["Geist"],
                },
                fontSize: {
                    "headline-md":  ["20px", { lineHeight: "28px", letterSpacing: "-0.01em",  fontWeight: "500" }],
                    "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em",  fontWeight: "700" }],
                    "headline-xl":  ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "600" }],
                    "headline-lg":  ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
                    "body-md":      ["14px", { lineHeight: "22px", letterSpacing: "0em",      fontWeight: "400" }],
                    "body-sm":      ["12px", { lineHeight: "18px", letterSpacing: "0.005em",  fontWeight: "400" }],
                    "body-lg":      ["18px", { lineHeight: "28px", letterSpacing: "0em",      fontWeight: "400" }],
                    "code-editor":  ["13px", { lineHeight: "22px", letterSpacing: "0em",      fontWeight: "400" }],
                    "label-badge":  ["11px", { lineHeight: "14px", letterSpacing: "0.04em",   fontWeight: "600" }],
                    "code-inline":  ["12px", { lineHeight: "16px", letterSpacing: "-0.01em",  fontWeight: "500" }],
                    "title-sm":     ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
                },
            }
        }
    }
</script>
